language: node_js
node_js:
  - 12.16.1

services:
  - docker

before_install:
  - docker build -t https://github.com/F3rnand3s/travis-docker-test .
  - docker run -p 3000:3000 -d f3rnand3s/dockernodejs-test
  - docker ps -a

script:
  - npm start